"$schema" = 'https://starship.rs/config-schema.json'

# TODO: better flow of fg/bg
# TODO: cleanup/combine format []
format = """
([](fg:error-bg)$status[](fg:error-bg))\
[](sys-bg)$os$username[](fg:sys-bg bg:dir-bg)\
$directory[](fg:dir-bg bg:git-bg)\
$git_branch\
([ ](bold fg:git-sep bg:git-bg)$git_status)\
[](fg:git-bg bg:lang-bg)\
($python)\
($nodejs)\
($rust)\
[](fg:lang-bg bg:docker-bg)\
($docker_context)[](fg:docker-bg)\
[  ](none)\
"""

# continuation_prompt = '$fill'
command_timeout = 1000
# Disable the blank line at the start of the prompt
# add_newline = false

palette = 'pastel'
[palettes.pastel]
sys-bg = '#9A348E'
dir-bg = '#DA627D'
git-bg = '#FCA17D'
git-sep = '#F95D1F'
lang-bg = '#86BBD8'
lang-sep = '#529EC7'
docker-bg = '#06969A'
error-bg = 'red'

[fill]
symbol = '∙'
style = 'bright-black'

[status]
format = "[$int]($style)"
style = "bold bg:error-bg fg:white"
disabled = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = false
style_user = "bg:sys-bg"
style_root = "bg:sys-bg"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:sys-bg"
disabled = false # Disabled by default
[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[directory]
style = "bg:dir-bg"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:lang-bg"
version_format = 'v${major}.${minor}'
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:docker-bg"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:lang-bg"
version_format = 'v${major}.${minor}'
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:lang-bg"
version_format = 'v${major}.${minor}'
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:git-bg"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:git-bg"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:lang-bg"
version_format = 'v${major}.${minor}'
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:lang-bg"
version_format = 'v${major}.${minor}'
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:lang-bg"
version_format = 'v${major}.${minor}'
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:lang-bg"
version_format = 'v${major}.${minor}'
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:lang-bg"
version_format = 'v${major}.${minor}'
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:lang-bg"
version_format = 'v${major}.${minor}'
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:lang-bg"
version_format = 'v${major}.${minor}'
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:lang-bg"
version_format = 'v${major}.${minor}'
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:lang-bg"
version_format = 'v${major}.${minor}'
format = '[ $symbol ($version)(/$virtualenv) ]($style)'
pyenv_version_name = true

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'
