"$schema" = 'https://starship.rs/config-schema.json'

##region General

##region Format Default
# format = """
# (\
# [](fg:alert-primary)\
# [$status ](bold bg:alert-primary fg:alert-secondary)\
# [](bold fg:alert-primary inverted)\
# )\
# [](fg:sys-primary)[$os( $username) ](bg:sys-primary)[](fg:sys-primary)\
# [ $directory ](fg:dir-primary inverted)[](fg:dir-primary)\
# (\
# [ $git_branch(  $git_status(  $git_state)) ](fg:git-primary inverted)\
# [](fg:git-primary)\
# )(\
# [( $python)( $nodejs)( $rust) ](fg:lang-primary inverted)\
# [](fg:lang-primary)\
# )(\
# [ $docker_context ](fg:docker-primary inverted)[](fg:docker-primary)\
# )\
# \n$character \
# """
##endregion

##region Format Minimal
format = """
([┆ $status ](bold fg:alert-primary))\
[  $os( $username) ](fg:sys-primary) [ $directory ](bold fg:dir-primary)\
( [( $git_branch)( $git_commit)( $git_status)( $git_state) ](fg:git-primary))\
( [( $python)( $nodejs)( $rust) ](fg:lang-primary) )\
( [( $docker_context)( $kubernetes) ](fg:docker-primary) )\
\n$character \
"""
##endregion

# continuation_prompt = '$fill'
command_timeout = 1000
# Blank line at the start of the prompt
add_newline = true

##endregion
##region Palettes

palette = 'dracula'
[palettes.pastel]
sys-primary = '#9A348E'
dir-primary = '#DA627D'
git-primary = '#FCA17D'
lang-primary = '#86BBD8'
lang-secondary = '#529EC7'
docker-primary = '#06969A'
alert-primary = 'red'
alert-secondary = "#FF0000"
[palettes.dracula]
sys-primary = '#FF79C6'
dir-primary = '#BD93F9'
git-primary = '#FFB86C'
lang-primary = '#8BE9FD'
lang-secondary = '#282A36'
docker-primary = '#8BE9FD'
alert-primary = '#FF5555'
alert-secondary = "#282A36"

##endregion
##region System

[fill]
disabled = true
symbol = ''
style = 'bright-black'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
format = ' $time'

[status]
disabled = false
symbol = "󰴔 $int"
success_symbol = "󰣐"
map_symbol = false
format = "$symbol"

[character]
disabled = false
format = "$symbol"
success_symbol = "[](bold fg:white)"
error_symbol = "[](bold fg:alert-primary)"

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
disabled = false
show_always = false
style_user = "bg:sys-primary"
style_root = "fg:alert-primary bg:sys-primary"
format = '[$user]($style)'

[os]
disabled = false
format = "$symbol( $version)"
[os.symbols]
Alpine = ""
Amazon = ""
Android = ""
Arch = ""
CentOS = ""
Debian = ""
DragonFly = ""
Emscripten = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Gentoo = ""
Linux = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = ""
Mint = ""
NetBSD = ""
NixOS = ""
OpenBSD = ""
openSUSE = ""
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
Redox = ""
Solus = ""
SUSE = ""
Ubuntu = ""
Unknown = ""
Windows = "󰖳"

[directory]
disabled = false
format = "$path"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󱔗"
"Downloads" = ""
"Music" = ""
"Pictures" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = ""
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important " = ""

##endregion
##region Git

[git_branch]
disabled = false
only_attached = true
truncation_length = 32
symbol = ""
format = '$symbol( $branch)'

[git_commit]
disabled = false
only_detached = true
tag_disabled = true
tag_symbol = ""
format = '( $hash)'

[git_status]
disabled = false
conflicted = " 󰜺"
ahead = " "
behind = " "
diverged = " 󱞫"
untracked = " 󱔢"
stashed = " "
staged = " "
renamed = " "
deleted = " "
modified = " "
up_to_date = " "
format = '(┆$all_status$ahead_behind)'

[git_state]
disabled = false
rebase = " "
merge = " "
revert = " "
cherry_pick = " "
bisect = " "
am = " "
am_or_rebase = " "
format = "(┆$state( $progress_current/$progress_total))"

##endregion
##region Environment

[c]
disabled = true
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[elixir]
disabled = true
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[elm]
disabled = true
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[golang]
disabled = true
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[haskell]
disabled = true
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[java]
disabled = true
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[julia]
disabled = true
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[nodejs]
disabled = false
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[nim]
disabled = true
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[rust]
disabled = false
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[scala]
disabled = true
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[python]
disabled = false
symbol = "󰌠"
version_format = '${major}.${minor}'
format = '$symbol( $version)(/$virtualenv)'
pyenv_version_name = false
python_binary =	['python3', 'python', 'python2']

[docker_context]
disabled = false
symbol = ""
format = '$symbol $context( $path)'
only_with_files = false
detect_files = [
    "docker-compose.yml", "docker-compose.yaml", "Dockerfile",
    "skaffold.yaml", "skaffold.yml"
]

[kubernetes]
disabled = false
symbol = "󱃾"
format = '$symbol $context( $starship-namespace)'
# detect_files = [
#     "docker-compose.yml", "docker-compose.yaml", "Dockerfile",
#     "skaffold.yaml", "skaffold.yml"
# ]

##endregion
