"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:alert-bg)[$status ](bold bg:alert-bg fg:alert-dim)[](bold fg:alert-bg inverted)\
[](fg:sys-bg)[$os$username ](bg:sys-bg)[](fg:sys-bg)\
[ $directory ](fg:dir-bg inverted)[](fg:dir-bg)\
(\
[ $git_branch(  $git_status( $git_state)) ](fg:git-bg inverted)\
[](fg:git-bg)\
)(\
[( $python)( $nodejs)( $rust) ](fg:lang-bg inverted)\
[](fg:lang-bg)\
)(\
[ $docker_context ](fg:docker-bg inverted)[](fg:docker-bg)\
)\
\n$character \
"""

# continuation_prompt = '$fill'
command_timeout = 1000
# Disable the blank line at the start of the prompt
# add_newline = false

palette = 'pastel'
[palettes.pastel]
sys-bg = '#9A348E'
dir-bg = '#DA627D'
git-bg = '#FCA17D'
lang-bg = '#86BBD8'
lang-dim = '#529EC7'
docker-bg = '#06969A'
alert-bg = 'red'
alert-dim = "#FF0000"

[fill]
disabled = true
symbol = ''
style = 'bright-black'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
format = ' $time'

[status]
disabled = false
symbol = " $int"
success_symbol = ""
map_symbol = false
format = "$symbol$maybe_int"

[character]
disabled = false
format = "$symbol"
success_symbol = "[](bold fg:white)"
error_symbol = "[](bold fg:alert-bg)"

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
disabled = false
show_always = false
style_user = "bg:sys-bg"
style_root = "fg:alert-bg bg:sys-bg"
format = '[$user]($style)'

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
disabled = false # Disabled by default
format = "$symbol"
[os.symbols]
Alpine = ""
Amazon = ""
Android = ""
Arch = ""
CentOS = ""
Debian = ""
DragonFly = ""
Emscripten = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = "﯑"
Gentoo = ""
HardenedBSD = "ﲊ"
Illumos = ""
Linux = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = ""
Mint = ""
NetBSD = ""
NixOS = ""
OpenBSD = ""
openSUSE = ""
OracleLinux = ""
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
Redox = ""
Solus = "ﴱ"
SUSE = ""
Ubuntu = ""
Unknown = ""
Windows = ""

[directory]
disabled = false
format = "$path"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = ""
"Downloads" = ""
"Music" = ""
"Pictures" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = ""
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important " = ""

[git_branch]
disabled = false
symbol = ""
format = '$symbol $branch'

[git_status]
disabled = false
conflicted = "ﰸ"
ahead = ""
behind = ""
diverged = "ﬕ"
untracked = ""
stashed = ""
staged = "樂"
renamed = "﬍"
deleted = ""
modified = ""
up_to_date = ""
format = '$all_status$ahead_behind'

[git_state]
disabled = false
rebase = "金"
merge = "ﰂ"
revert = "ﯰ"
cherry_pick = ""
bisect = ""
am = ""
am_or_rebase = "ﰮ"
format = "$state( $progress_current/$progress_total)"

## Languages

[c]
disabled = true
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[elixir]
disabled = true
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[elm]
disabled = true
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[golang]
disabled = true
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[haskell]
disabled = true
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[java]
disabled = true
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[julia]
disabled = true
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[nodejs]
disabled = false
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[nim]
disabled = true
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[rust]
disabled = false
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[scala]
disabled = true
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)'

[python]
disabled = false
symbol = ""
version_format = '${major}.${minor}'
format = '$symbol( $version)(/$virtualenv)'
pyenv_version_name = true

[docker_context]
disabled = false
symbol = ""
format = '$symbol $context $path'

