[tools]
python = "3.12"
node = "20"
kubectl = "1.33"
"pipx:nbdev" = "latest"
"pipx:jupyterlab" = { version = "latest", uvx_args = "--with polars --with pandas --with dask" }
jira-utils = "latest"

[tool_alias]
jira-utils = "pipx:git+https://github.huit.harvard.edu/jic012/jira-utils.git"

[settings]
idiomatic_version_file_enable_tools = ["python", "node"]
